version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - ">= 5.a, < 6"
  - dependency-name: "@jupyterlab/application"
    versions:
    - 3.0.7
    - 3.0.8
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
