# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up dependencies
      run: |
        npm ci
        npm run setup:python
        npm run build
        .venv/bin/jupyter labextension link .
    - name: Test the theme
      run: |
        .venv/bin/jupyter labextension list 2>&1 | grep -ie "jupyterlab_city-lights-theme.*OK"
        npm test
      env:
        CI: true
